name: FillInTheWall
version: '1.1'
main: com.articreep.fillinthewall.FillInTheWall
api-version: '1.20'
softdepend: [NoteBlockAPI]
commands:
  fillinthewall:
    description: testing commands
    usage: /fillinthewall <spawn/custom/hotbar/pair/spectate>
    aliases: [hitw, holeinthewall, fitw]
  registerplayingfield:
    description: Used to create a playing field and register it to config
    usage: /registerplayingfield
