name: FillInTheWallLite
version: '1.0'
main: com.articreep.fillinthewall.FillInTheWallLite
api-version: '1.20'
commands:
  fillinthewall:
    description: testing commands
    usage: /fillinthewall <custom/hotbar>
    aliases: [hitw, holeinthewall, fitw]
  registerplayingfield:
    description: Used to create a playing field and register it to config
    usage: /registerplayingfield
